export const GET_ALL_CINEMA = "GET_ALL_CINEMA";
export const GET_LIST_CINEMA_CLUSTERS = "GET_LIST_CINEMA_CLUSTERS";
export const SELECT_CINEMA = "SELECT_CINEMA";
export const GET_LIST_CINEMA_RELEASE = "GET_LIST_CINEMA_RELEASE";

export const GET_SHOWTIME_ID = "GET_SHOWTIME_ID";
export const GET_SEAT = "GET_SEAT";
